### ISSUE TITLE
No AutoFill in Reddit app

### ISSUE THREAD

**Issue by Offerel** [Kunzisoft/KeePassDX#1572]
**Describe the bug**
I have tried to insert credentials into the reddit app, but there seems to be no AutoFill available.

**To Reproduce**
1. Install official reddit app 
2. Open app
3. Click on already existing user
4. No AutoFill suggestions 

**Expected behavior**
With Keepass2Android using the same database, AutoFill is suggested at the same.

**KeePass Database**
 - Created with: [Linux KeePassXC 2.7.4]
 - Location: [local]
 - KeePassDX from F-Droid 

**Android:**
 - Device: [e.g. GalaxyS23+]
 - Version: [13]

**Additional context**
 - Browser for Autofill: [Reddit app ]

**Comment by J-Jamet** [comment]
It's not possible to force an app that doesn't want autofill to have it. Contact the Reddit team to change this behavior on their app.

**Comment by Offerel** [comment]
Normally I try to not compare both, but with Kp2A I can make use of AutoFill with the Reddit app. Do you know if they use some other thing?

It's not only this app, there are other apps with the same behavior. I used it only as prominent example.

**Comment by J-Jamet** [comment]
Ho OK it's weird. I'll test it with KeePass2Android.

**Comment by Offerel** [comment]
Hmm weird. In my case it looks like this. One screenshot is with enabled integration into the keyboard and one without.

![Screenshot_20231021_084709_Reddit](https://github.com/Kunzisoft/KeePassDX/assets/14041522/c7b3de5a-dcf9-4121-a839-b94cc57f25b6)

![Screenshot_20231021_084554_Reddit](https://github.com/Kunzisoft/KeePassDX/assets/14041522/bb6ad992-2196-4936-9118-4f5ed5867ec9)

This are my settings:
![Screenshot_20231021_082838_Keepass2Android](https://github.com/Kunzisoft/KeePassDX/assets/14041522/0eb4bc64-7103-4829-877f-2ad23b6d8f4d)
![Screenshot_20231021_082852_Keepass2Android](https://github.com/Kunzisoft/KeePassDX/assets/14041522/756716e3-bff8-48bf-b053-79a64079c753)

**Comment by Offerel** [comment]
I don't know if the root cause is the same, but I have found the following with the app "Eternity for Lemmy". If I try to add a new account with KeePassDX set to AutoFill, it only trigger the AutoFill for the password field. If i focus the username, no AutoFill comes in. Not as pop-up, nor as Keyboard integration. If I however focus the password field, my Lemmy account is integrated into Gboard Keyboard. If I use the entry, the password is filled in, after that it changes the focus to the 2fa field and enters the username. I have downloaded Eternity from F-Droid, but you can find it also on the playstore or on [GitHub](https://github.com/Bazsalanszky/Eternity)

**Comment by J-Jamet** [comment]
Okay, now I get it. I tested the Reddit application with the registration form and no login, which are very similar.
I've just corrected the other [issue](https://github.com/Kunzisoft/KeePassDX/issues/1665#issuecomment-1793425464), and I have no problems filling in the form with KeePassDX.

**Comment by J-Jamet** [comment]
Fixed in 4.0.3

**Comment by alexknop** [comment]
I am still not getting a prompt on the Reddit app nor the SharkClean app.
I am getting prompts when using Keepass2Android.
However I did get a prompt for my Sonos, Apple Music and ProtonMail apps, so I know that KeePassDX is working across some apps on my device.

**Comment by J-Jamet** [comment]
![reddit_autofill](https://github.com/Kunzisoft/KeePassDX/assets/19224038/35504067-e480-456f-8dd4-1107f93cc2a3)

The form field recognition algorithm works for Reddit, I can't do anything more from KeePassDX.

**Comment by alexknop** [comment]
My Login screen looks slightly different. Couldn't get a direct screenshot cause my device was blocking it for security reasons.
![IMG_0875](https://github.com/Kunzisoft/KeePassDX/assets/11878115/13206fda-d19a-4deb-9643-d5f030e52531)

It may be because I'm running Android 13 and they have a different style applied than other OS versions.
However if it is the app itself showing this style, I am running the Reddit app version 2023.43.0, hopefully you are too.

**Comment by J-Jamet** [comment]
Indeed, I just saw that I did not have an up-to-date version of Reddit, after updating the autofill is not displayed. I don't know if this is a bug, or that Reddit knowingly prevented autofill.
Android 13 is not the cause

**Comment by alexknop** [comment]
SharkClean...
I wonder if the issue is the Username/Email and Password words are "embedded" in the fields themselves versus being above/outside of them. Reddit app is similar.
![Screenshot_2023-11-06-13-15-01-486](https://github.com/Kunzisoft/KeePassDX/assets/11878115/160b5dcc-5642-4f47-ba1e-43ae78d804eb)

**Comment by J-Jamet** [comment]
OK, so I debugged and I found very surprising behavior in the logs. The algorithm detects hundreds of password fields for the Reddit application while it detects only one in the other forms in which it works.
As the KeePassDX algorithm only stores the first password field to optimize parsing memory, this view seems to no longer be present at the end of the parse.
But always storing the last recovered password view solves the problem. I imagine there is a verification system that destroys and rebuilds field views on the fly. So I will apply the fix based on the principle that the last parsed view is the correct one.

**Comment by J-Jamet** [comment]
I've been struggling to find the right middles for the right recognition, but it works as well as I can otherwise it takes away recognition on other types of forms. You can try version 4.0.4.

**Comment by alexknop** [comment]
I'm finding that if I press the Username field first it doesn't suggest a login from Keepass, but if I then press the Password field it does.
Similarly, I can press the Password field first and it won't suggest a login, but then I can press the Username field and it will suggest one.

**Comment by J-Jamet** [comment]
So that means the algorithm is working. Typically I don't know why hundreds of views are parsed in this app, there must be a refresh in the form. I've done a lot of testing and I can't do any better without messing up the other form fillers.
