### ISSUE TITLE
Username is not filled in android browser

### ISSUE THREAD

**Issue by jmichler** [Kunzisoft/KeePassDX#1665]
**Describe the bug**

Since some months the username filled is no longer filled through autofill service of android. This is a Galaxzy S21 with latest android 13 and latest chrome. The issue is also there on Firefox.

I'm not getting suggestions in the username field and if I enter the password field I get them but only the password is filled then.

I'm sure this worked earlier.

**To Reproduce**

1. Enable keepassdx as the autofill service
2. Open a page with a password in KeePass, e.g. Kunde.comdirect.de
3. Click the username field=> no suggestions
4. Click the password field => suggestions.
5. Select an entry from the suggestions
6. Passwort is filled but username is NOT

**Expected behavior**

In step 6 also the username should be filled

**KeePass Database**

 - Created with: windows keepass
 - Version: 2
 - Location:  Remote file retrieved with onedrive 
 - File provider (`content://` URI): [onedrive]
 - Size: 1Mb
 - Contains attachment: no

**KeePassDX:**

 - Version: 4.0.2
 - Build: free
 - Language: german

**Android:**

 - Device: Galaxzy s21
 - Version: 13

**Additional context**

 - Browser for Autofill: Chrome 117

**Comment by inzaghi89** [comment]
The same issue is in Firefox. Only password are filled

**Comment by esodigoyo** [comment]
Username is filled in the web address field in my case

**Comment by Tommy-01** [comment]
Same Problem here, with an up-to-date Pixel 6 with GrapheneOS using Fennec as Browser.
The problem has existed for me for several months.

**Comment by jmichler** [comment]
And it seems to be a problem of the app itself. In the Keepass2Android app it is still working, so I think it is not google to blame this time for a autofill issue;-)

**Comment by marko-pi** [comment]
I have Samsung Galaxy S10E, use Chrome and have the same issue.

**Comment by seba174** [comment]
Same for me, the issue happens occasionally, always for user/email fields. Didn't have any issues for example with Keepass2android

**Comment by nicoursi** [comment]
As a workaround, after the password gets filled just type the first letter of the username and you'll get prompted again, this time it'll work

**Comment by ginkel** [comment]
Is this limited to Chrome? I'm also seeing this with the current Edge release.

**Comment by EntityinArray** [comment]
Having the same issue, in Chrome Android username gets filled into the address bar.

**Comment by J-Jamet** [comment]
OK guys, The autofill system depends on many parameters: 
 - The autofill service of the machine
 - The browser used
 - The form parsed

In order to be able to debug correctly, please indicate in each comment :
 - The Android version you're using and your device
 - The browser you're using and its exact version
 - The url of the form you're trying to access
 - The exact problem you're facing

Otherwise I won't be able to identify each problem. I'm already going to focus on the parameters of those of @jmichler who filled in his bug report correctly.

Please note that if the service works for browsers with native Autofill but not with browsers in compatibility mode, I won't be able to do much. But there may be browsers switching from one mode to another, we need to know from which version of the browser autofill is supported or is no longer supported to update the file : https://github.com/Kunzisoft/KeePassDX/blob/master/app/src/main/res/xml/dataset_service.xml

**Comment by EntityinArray** [comment]
Hi, thank you for working on this!
I recorded a video that demonstrates the issue:

https://github.com/Kunzisoft/KeePassDX/assets/18554021/85638f6b-c15c-4897-8e6a-1cbf34e4a72d

In my case:
 - Autofill service:
![Screenshot_2023-10-29-09-30-05-719_com android settings](https://github.com/Kunzisoft/KeePassDX/assets/18554021/0c45a197-c326-414f-b72d-b717354f25ee)
- Browser used:
![Screenshot_2023-10-29-09-30-45-071_com miui securitycenter](https://github.com/Kunzisoft/KeePassDX/assets/18554021/a0e9281e-d2be-4ba0-9ec8-411825c24dd4)
- The form parsed:
Any form fills the username into the browser's address bar.

**Comment by J-Jamet** [comment]
Fixed with https://github.com/Kunzisoft/KeePassDX/issues/1508#issuecomment-1793424670
https://github.com/Kunzisoft/KeePassDX/commit/2d8f8aeef33e6994312cbc81844ba7b9670ce8fb

**Comment by J-Jamet** [comment]
Fixed in 4.0.3

**Comment by brianjmurrell** [comment]
I still have this problem on 4.0.5 with Android 13 and Chrome 120.0.6099.231 (Official Build) (32-bit).  Example site is GitHub login but it happens with every website login I try. Another specific example is https://frame.work/login.

**Comment by the-three-moirai** [comment]
I confirm it too. Few months ago I started using AuthPass (also available in F-Droid) just for auto fill while using KeePassDX for managing everything else on my keepass DB as a workaround, as it's a much better application.

It's been working flawlessly.

**Comment by J-Jamet** [comment]
The algorithm is permissive, but it seems that the autofill service takes a long time on some devices and prevents the username from being recognized. But if you insist, it works.
This will be resolved when the algorithm engine works differently for each site, but it's a huge job: https://github.com/Kunzisoft/KeePassDX/issues/1287

**Comment by glemco** [comment]
Thanks @J-Jamet for your time in trying to fix this, it doesn't seem trivial at all!
However, I'd propose a kind of workaround: every time this happens (as said, on some sites, not always, insisting usually doesn't help in my case), I have to open the database, look for the entry, and copy the username, this is rather annoying.
Would it be possible to have the clipboard notification appear every time the autofill is triggered? At least it would be easy to copy the username with just one tap.

**Comment by schnillerman** [comment]
+1 here.

![Screenshot_20240218_101802_Settings.jpg](https://github.com/Kunzisoft/KeePassDX/assets/17252473/08021425-74e6-4f97-a803-86e50cb7240d)

Mozilla Firefox:

122.1.0 (Build #2016001831), 0d66540568+
GV: 122.0.1-20240205133611
AS: 122.0.1

URL:

https://www.kununu.com/de/login

**Comment by inzaghi89** [comment]
Few days ago I've switched back to keepass2android and there is no problem with autofill on Android 14 and Firefox. I will be happy if keepassdx can handle thisz so I can switch back.

**Comment by Ironfist69** [comment]
Same issue

- Android 14
- OneUI 6
- Samsung Galaxy A13
- Samsung Default Keyboard
- Chrome 122.0.6261.90

**Comment by mrkobel** [comment]
still experiencing the issue:
v 4.0.5
latest chrome
fully patched samsung s21
morele.net password form
Google keyboard

**Comment by tobiaslangner** [comment]
I'm also affected by this issue but wanted to stress (maybe once more) that autofill **in general** works fine, but it does not fill the username but only the password. 

I noticed the issue in the past that the autofill dropdown often did not show up when clicking on the username textbox but clicking on the password textbox usually brought it up. In the past, selecting the right entry there filled both password and username, now I've noticed on many pages where this used to work in the past that **only** the password is filled.

This is exactly the same behavior as described and show in the video [above](https://github.com/Kunzisoft/KeePassDX/issues/1665#issuecomment-1784014018).

**Comment by EetuRasilainen** [comment]
I solved this by switching to Keepass2Android. Auto-type is fully working there, including the username fields.

**Comment by shortwavesurfer2009** [comment]
I ended up commenting on an issue that was a duplicate of this one that got closed recently. So here is what I said in the other comments section.

> I am having this same problem and it has been going on for quite a long time. I actually came here to create a new issue for this exact thing, but ran across this one first.

> Edit:
> Android 13
> KeepassDX 4.0.5
> Fennec 124.2.0 based on firefox 124.2.0

**Comment by J-Jamet** [comment]
@shortwavesurfer2009 
I can reproduce the bug with Firefox 124.2.0 but not with DuckDuckGo 5.163.0, I don't know why Firefox and Fennec behave this way.

**Comment by J-Jamet** [comment]
I've just debugged, I don't know where it's coming from but by removing an optimization parsing element, I can get it to work on Firefox.

**Comment by auanasgheps** [comment]
I am seeing the same issue with Brave. Will report with 4.10 once it's released.

**Comment by brianjmurrell** [comment]
> J-Jamet added a commit that referenced this issue 17 hours ago
> fix: Fix username recognition with firefox #1665
27ea357

Awesome news!

How long does it take for something like this to reach [the great unwashed](https://www.merriam-webster.com/dictionary/the%20%28great%29%20unwashed) (i.e. show up the Google Play Store)?

**Comment by shortwavesurfer2009** [comment]
@brianjmurrell google play? 🤮

F-droid is the place to be

**Comment by brianjmurrell** [comment]
> @brianjmurrell google play? 🤮
> 
> F-droid is the place to be

Has the app been updated in F-droid at this point then?  My F-droid is only showing 4.0.5 there.

Generally speaking I would love to use F-droid a lot more than I do.  I love everything about F-droid except for one (very big) thing.  It has no concept of remembering what I have installed on my device(s).  So when I get a new device I have to **remember** which 2 dozen apps I install from it and then I have to go manually install all 2 dozen of those apps.  I have neither the memory for that or the patience to (a) keep a written list (updated) of apps I install from it and (b) manually install all of those apps every time I get a new device or have to factory reset it (and/or clean-flash a new ROM on it).

If F-droid would address just that one issue, it would be my primary, go-to app store in a heart-beat.

**Comment by leowankerddd** [comment]
I'm using a Samsung Galaxy S21 with Android 14.
I've tested a few different browsers and including the standard Google Chrome and none of them work for populating the user ID.
I have hopefully temporarily switched to keepass2android because it works .

**Comment by J-Jamet** [comment]
@leowankerddd What is the URL and the form reproducing the issue?

**Comment by auanasgheps** [comment]
@J-Jamet honestly EVERY website shows this issue, even github.com doesn't pick up the username field.
Brave 1.64.122
Android 14
KeepassDX 4.0.5

**Comment by J-Jamet** [comment]
I've been debugging and I don't understand why it works fine on Chrome but not on Brave : 

```
2024-04-16 20:37:39.359 12876-12876 com.kunzis...illService com.kunzisoft.keepass.free           D  Autofill requested in compatibility mode
2024-04-16 20:37:39.367 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill applicationId: com.android.chrome
2024-04-16 20:37:39.367 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill username candidate android text type: 0x00000001
2024-04-16 20:37:39.367 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill password android text type: 0x000000e1
2024-04-16 20:37:39.368 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill domain: github.com
2024-04-16 20:37:39.368 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill scheme: https
```

```
2024-04-16 20:37:51.418 12876-12876 com.kunzis...illService com.kunzisoft.keepass.free           D  Autofill requested in compatibility mode
2024-04-16 20:37:51.421 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill applicationId: com.brave.browser
2024-04-16 20:37:51.422 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill password android text type: 0x00000081
2024-04-16 20:37:51.422 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill domain: github.com
2024-04-16 20:37:51.422 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill scheme: https
2024-04-16 20:37:51.422 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill username candidate android text type: 0x00080001
2024-04-16 20:37:54.880 12876-12876 com.kunzis...illService com.kunzisoft.keepass.free           D  Autofill requested in compatibility mode
2024-04-16 20:37:54.882 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill applicationId: com.brave.browser
2024-04-16 20:37:54.882 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill password android text type: 0x00000081
2024-04-16 20:37:54.882 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill domain: github.com
2024-04-16 20:37:54.882 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill scheme: https
2024-04-16 20:37:54.882 12876-12876 com.kunzis...tureParser com.kunzisoft.keepass.free           D  Autofill username candidate android text type: 0x00080001
```

**Comment by auanasgheps** [comment]
Just to confirm, I installed the old Keepass2Android and it is able to autofill in Brave just fine.

**Comment by J-Jamet** [comment]
It comes from the recognition algorithm implemented in KeePassDX, that's for sure, but I've yet to understand the implementation of the view tree in brave. Here it's as if the edit text field was recognized after the password field, but not interpreted, I don't know why.

**Comment by brianjmurrell** [comment]
Just to be perfectly clear, this problem is **NOT** limited to Brave.  This problem happens in Chrome also.  In fact the initial description on this ticket specifies Chrome and I can confirm that I only use Chrome on my devices.

**Comment by J-Jamet** [comment]
The ticket indicates chrome but I had already made improvements to the algorithm, I reopen the ticket to keep track of the history. On the github.com/login form, I have no problems with chrome.

**Comment by brianjmurrell** [comment]
Ahh.  OK.  Are those Chrome improvements yet to be made available in a (Google Play Store) release?

**Comment by auanasgheps** [comment]
@J-Jamet even if it's a bug in Brave... with Keepass2Android works just fine

**Comment by J-Jamet** [comment]
I get it, repeating the same thing doesn't advance the issue! Without understanding why it works on KeePass2Android more than KeePassDX, I can't make a fix without opening a security hole.
So I investigated, there is indeed a regression in the nodes visible in brave, the username node types are always at 
InputType.TYPE_NULL -> 0x00000000
I've just made a first implementation, which I don't really like but seems to work in a few cases, using the className parameter to identify whether the view is editable text and putting it as a username candidate if it's before the password field.

![Screenshot_20240419_132338](https://github.com/Kunzisoft/KeePassDX/assets/19224038/202cb41b-d80c-4a14-abe1-cf8f65119994)

This doesn't seem to be enough to fill in other forms correctly. On Gitlab, only the username field is filled in, not the password. I'll try to further improve the algorithm.

**Comment by J-Jamet** [comment]
I did the commit after a bit of cleaning and it works fine. Will be fixed in version 4.1.0

**Comment by leowankerddd** [comment]
> @leowankerddd Which URL and form reproduce the issue?

Go to
https://freefilesync.org and go to The Forum section and there is an option to log in and other password managers properly pop up automatically to enter the user ID and password.


I've tried changing keyboards and even attempted to use the magic keyboard but I can't get that to work consistently if I go into settings and make it my default keyboard the first time I can get into keepass DX and then if I tap on the keyboard icon on the screen it sets the default back to Samsung.

I've tried multiple browsers including the built-in Google Chrome.

I've been doing some reading about adding password managers to the accessibility feature inside the operating system and I think I read some reluctance to wanting to add the software to accessibility for some reasons that I don't understand completely. I use a variety of password managers including bit Warden and keypass2 Android and both of them are in accessibility. Would it be possible to reconsider adding he passed DX to accessibility to make it at least work or to have an option available to make it work?

I don't see/understand the risk in adding it to accessibility. I have an accessibility icon in the lower right hand corner of my display and can activate it at will and it would be nice to have DX in there also.

**Comment by J-Jamet** [comment]
> I've tried changing keyboards and even attempted to use the magic keyboard but I can't get that to work consistently if I go into settings and make it my default keyboard the first time I can get into keepass DX and then if I tap on the keyboard icon on the screen it sets the default back to Samsung.

Magikeyboard doesn't use form recognition at all, it's a completely separate feature.

> I've been doing some reading about adding password managers to the accessibility feature inside the operating system and I think I read some reluctance to wanting to add the software to accessibility for some reasons that I don't understand completely. I use a variety of password managers including bit Warden and keypass2 Android and both of them are in accessibility. Would it be possible to reconsider adding he passed DX to accessibility to make it at least work or to have an option available to make it work?

https://github.com/Kunzisoft/KeePassDX/wiki/AutoFill#why-not-use-the-accessibility-service
https://github.com/Kunzisoft/KeePassDX/issues/551#issuecomment-629761239

**Comment by leowankerddd** [comment]
> I have just tested the new algorithm in version 4.1.0 with the forum login form of https://freefilesync.org/ and it works fine ;)

May I "beta" test 4.1.0 or will it be out soon enough that it won't really matter that much?

**Comment by leowankerddd** [comment]
I see that it's closed I just wanted to leave a message that I installed this new version and it works to autofill. Thank you.

**Comment by georgh-** [comment]
Just came to thank you for fixing it, this app is so much better than the alternatives! 

I made a donation and encourage everybody to do the same. We should all be supporting the Free software we use and enjoy.

**Comment by brianjmurrell** [comment]
> I'm currently creating version 4.0.6, which contains the Autofill resolutions. It will be available later today.

Where was it released to?  Google Play Store?  Any idea how long that takes to become available after you "release" it there?  Still not seeing it in my available updates.

**Comment by b-a0** [comment]
> Where was it released to?
I see it in my Google Play Store (not F-Droid), but only on the account that is enrolled into the beta. [This link shows](https://www.androidpolice.com/how-to-sign-up-for-an-app-beta-through-the-google-play-store/) how to enroll in the beta.

**Comment by brianjmurrell** [comment]
Ahh.  Was it released as a beta (only)?

**Comment by leowankerddd** [comment]
The only place I found the new release was right here on GitHub. I needed to uninstall the version from the Google Play app store before the one from GitHub would install.

**Comment by J-Jamet** [comment]
When a new version is released, Github is updated with APKs signed by myself. The free apk is then re-signed by Google and sent to the Play Store beta channel, and I wait about a week before putting it into production if no problems have been reported. The F-Droid version updates when the server passes on the tag and builds the APK from source, so it may take longer.
