### ISSUE TITLE
Low memory

### ISSUE THREAD

**Issue by kunago** [Kunzisoft/KeePassDX#183]
I wanted to ask what might be the cause of low memory announcement? I am unable to open the database with KeePassDX but some other programs work as they should (KeePass2Android). Might that be because of attachments as was pointed in #115 or should I think of a different reason? Is there a way to debug?

**Comment by J-Jamet** [comment]
If you have a memory problem it is probably due to attachments that are not yet supported. I'm working on it and it will be solved in the next update with the addition of a temp memory.

**Comment by kunago** [comment]
This is very likely the case but I would not KeePassDX expect to support any attachment possible. In my DB I have various non-standard files which are obviously usable only on some devices.

**Comment by J-Jamet** [comment]
Don't worry, file types have nothing to do with storage.
The problem is just that the data parser is not big enough for big binaries, so I make sure to serialize them into temporary memory for later recovery. I don't have to read them for the moment, just move them. After, for the reading, I'm going to use other applications.

**Comment by J-Jamet** [comment]
Normally corrected with version 2.5.0.0beta18, tell me if it's ok for you.

**Comment by juwancase** [comment]
This issue still persists on 2.5.0.0beta18.
Logcat: https://pastebin.com/qXcUeq0i

- App version: 2.5.0.0beta18
- Android version: 9
- Database settings:
  - Encryption: ChaCha20
  - Key derivation: Argon2
  - Transform rounds: 12
  - Memory usage: 64MB
  - Parallelism: 4
  - Size: < 210KB
