### ISSUE TITLE
Auto-fill popup wont show entry

### ISSUE THREAD

**Issue by dmework** [Kunzisoft/KeePassDX#1936]
**Describe the bug**

Auto-fill popup wont show entry unless URL is exact without even “https”

**To Reproduce**

1. If URL field contain “github.com”
2. Autofill popup show entry to fill username and password
3. But If URL field contain “https://github.com” or “https://github.com/login”
4. Autofill popup don’t show entry to fill username and password

**Expected behavior**

Auto-fill popup show Entry no matter what the URL parameters are
This issue doesn’t exist in KeePassDX version 4.0.8

**KeePass Database**

 - Created with: Android KeePassDX
 - Version: 4.1.0
 - Location: phone memory
 - Size: 2.45
 - Contains attachment: No

**KeePassDX:**

 - Version: 4.1.0
 - Build: Libre
 - Language: English

**Android:**

 - Device: Galaxy S8
 - Version: 9.0

**Additional context**

 - Browser for Autofill: Cromite 131.0.6778.86 Android

**Comment by draekster** [comment]
I have the same problem with LineageOS 21 (Android 14) since 4.1.0.

Everytime I have to find and select the correct entry manualy. Sometimes the autofill popup does not appear too.

**Comment by J-Jamet** [comment]
This issue is linked to https://github.com/Kunzisoft/KeePassDX/issues/1820#issuecomment-2486720178, problem is solved in development, I make other patches and create the version 4.1.1.

**Comment by dmework** [comment]
Still not working in KeepassDX version 4.1.1 if URL field contain "https://github.com/login"

**Comment by J-Jamet** [comment]
The problem is addressed in the issue https://github.com/Kunzisoft/KeePassDX/issues/1940
