### ISSUE TITLE
Cannot use fingerprint login with LineageOS

### ISSUE THREAD

**Issue by Glamhoth** [Kunzisoft/KeePassDX#215]
Hello. I have problem on my Redmi 4X running LineageOS 15.1, after putting in the password and touching fingerprint sensor it doesn't log me in. Logcat file with error below.
[logcat.txt](https://github.com/Kunzisoft/KeePassDX/files/2645126/logcat.txt)

**Comment by romaroman** [comment]
Same problem, same device and ROM :disappointed:

**Comment by meowchin** [comment]
Funny, the same exact problem here. It worked fine on stock ROM.

**Comment by Glamhoth** [comment]
I think it's also worth to mention that I had no problem with fingerprint login on LineageOS 14

**Comment by J-Jamet** [comment]
The problem has been identified for the device:
Huawei Mate 20 pro
Android 9
Security Update 2019-03-01
Kernel : 4.9.9.7
Huawei Kirin 980
LYA-L29

I have to prioritize developments and I do not have much time, sorry if the resolution of fingerprint issues takes time.

**Comment by J-Jamet** [comment]
The problem should be solved with version 2.5.0.0beta23, tell me if it's OK for you?

**Comment by Glamhoth** [comment]
Unfortunately I'm still getting an exception when trying to save a fingerprint. My OS and hardware didn't change since then. I'm including log from logcat, which seems almost identical to the first one. 
[log.txt](https://github.com/Kunzisoft/KeePassDX/files/3619536/log.txt)

**Comment by J-Jamet** [comment]
Okay, I think it's really a concern in the OS and I can not do anything more on my side.
What you can try:

- Delete fingerprint keys in "Settings / Advanced unlock / Delete encryption keys"
- Delete all the fingerprints of your device and re-register them
- Manually delete the keystore file for keepass in "/data/misc/keystore/user_0/".
- Update the Lineage OS version

**Comment by porjo** [comment]
I had this issue also with Redmi Note 4 running LineageOS 16. In addition to clearing the keys, I also had to uninstall then re-install keepassdx before fingerprint function would work. Not sure if relevant, but my banking app uses fingerprint to unlock and I've never had an issue with it.

FYI, for anyone else with this phone: there is a bug with LineageOS where you can't delete the fingerprint keys the normal way. Instead you must first rename the key, then delete it.

**Comment by Offerel** [comment]
Some stupid question: How do i clear the keys? I tried it with Keepass2Android and KeepassDX, both do not work with Fingerprint on LineageOS (16 and 17.1). Does that mean, i should clear the keys inside of KeepassDX, remove then KeepassDX and reinstall it, or should i remove the Fingerprint in the OS via OS Settings? Fingerprint is working fine to unlock the device, but it cant use it with KeepassDX (or KP2A). On Stock ROM it works fine. Any Tips and detailed instructions would be helpful.

**Comment by J-Jamet** [comment]
It is possible that in your ROM version, the Keystore is not correctly integrated with the fingerprint manager. In this case, there is not much to do, you can try to delete the key from the keystore if there is one, but if it is not possible to create one associated with a fingerprint you will not be able to have this feature with the LineageOS rom.
https://github.com/Kunzisoft/KeePassDX/wiki/Advanced-Unlocking#errors

**Comment by Offerel** [comment]
Yes, this is the article I have read also. I would try to delete the key from the keystore, but I have no idea how I can do that. I can delete the scanned fingerprint, but I fear this is not what the article means.

**Comment by J-Jamet** [comment]
The fingerprint key corresponds to a keystore key. The problem with these custom OS is that the key management is not done correctly, I don't know why, we should look in detail in the ROM's source code.

**Comment by Offerel** [comment]
I have taken the ROM from this thread: https://forum.xda-developers.com/s7-edge/development/beta-lineageos-17-0-s7-edge-build-1-t3979973. I have no idea if the source code is available somewhere on GitHub. But it seems to be a generally LineageOS issue. Since the above ROM is currently not a official one, there is no official support from the LineageOS team. But maybe the developer can help you. I have no idea what i could ask him in detail.

**Comment by J-Jamet** [comment]
I completely refactored biometric recognition in version 2.9.5, tell me if that solves the problem? Otherwise you can still use the unlocking of the device.

**Comment by Offerel** [comment]
Nice. I will test this tomorrow and report if it works, i case of a Samsung device and LineageOS.

**Comment by Offerel** [comment]
I can confirm, that I can unlock the database now also on LineageOS. At least its working when I use device unlock method.

Nice work. Many, many thanks for this. This makes usage a lot easier for me.

**Comment by DrVektor** [comment]
xiaomi redmi note 5a prime lineageos 20 official from lineage os website. Fingerprint not working.

**Comment by J-Jamet** [comment]
Using a custom OS may prevent the system from saving keys in the KeyStore (thus using biometrics) because the OS implementation is not recognized by the hardware signature.

**Comment by DrVektor** [comment]
> Using a custom OS may prevent the system from saving keys in the KeyStore (thus using biometrics) because the OS implementation is not recognized by the hardware signature.

how can i fix this?
