### ISSUE TITLE
With Android 15, using a Teclast T50 11", in landscape format,..

### ISSUE THREAD

**Issue by idova01** [Kunzisoft/KeePassDX#2198]
### Checks

- [x] I have read the Wiki, searched the open issues, and still think this is a new bug.

### Explain the problem clearly and succinctly:

With Android 15, using a Teclast T50 11", in landscape format, 16:9, it is not possible to close the window because the button is not visible.
Unfortunately, a hard copy is not possible.
The image is simply cut off at the bottom, as if KeepassDX does not fit on the screen or the window is too small. You cannot click on the button at the bottom left to lock it. However, you can do this via the menu. You just have to figure it out first.

### KeePassDX version:

4.1.8

### Build:

Free

**Comment by chenxiaolong** [comment]
I've just submitted PR #2200, which (if accepted) should fix this.

**Comment by idova01** [comment]
I just tried version 4.2.0 Beta02 and unfortunately still have the same problem.
It would be good if you could make hard copies so I could post a picture here. I'll try to take a photo with my smartphone.

**Comment by idova01** [comment]
I've tried this platform, I actually uploaded a picture. No idea where to find it now. Sorry.

**Comment by idova01** [comment]
Pic

**Comment by J-Jamet** [comment]
I will release version 4.1.9 to address this issue. Thank you @chenxiaolong
