### ISSUE TITLE
Keepass field references

### ISSUE THREAD

**Issue by markcs** [Kunzisoft/KeePassDX#61]
Keepass allows field references in usernames and passwords.  From [https://keepass.info/help/base/fieldrefs.html](https://keepass.info/help/base/fieldrefs.html)

> KeePass can insert data stored in different entries into fields of an entry. This means that multiple entries can share a common field (user name, password, ...), and by changing the actual data entry, all other entries will also use the new value.

KeePassDX copies the reference text and NOT the actual reference value.

**Comment by J-Jamet** [comment]
Thx for the reply, I'll try to solve this rapidly.

**Comment by J-Jamet** [comment]
It's now fixed in the new version 2.5.0.0beta8.

**Comment by swedneck** [comment]
The latest version on F-Droid still has this issue.

**Comment by Suncatcher** [comment]
Confirm this, I am on the latest version and the issue is NOT resolved. Why it is closed?

**Comment by J-Jamet** [comment]
I coded a fix and retested, maybe there was a regression.

**Comment by J-Jamet** [comment]
I just tested::
Username Magikeyboard Ref -> OK
Password Magikeyboard Ref -> OK
Username Clipboard Notification Ref Copy -> OK
Password Clipboard Notification Ref Copy -> OK
Username Clipboard Button Ref Copy -> **KO**
Password Clipboard Button Ref Copy -> **KO**
Username Autofill Ref -> OK
Password Autofill Ref -> OK

**Comment by J-Jamet** [comment]
I fixed the problem in development, I added the references for custom fields.

**Comment by Skycoder42** [comment]
It does not work for the magic keyboard! I have entries with a custom attribute named "E-Mail". My username references it as "{S:E-Mail}", but the reference is not resolved by the keyboard!

**Comment by fritut08** [comment]
It does not work for me either. I have a password referenced via UUID as {REF:P@I:xxxxxxxxxxxxxxxxxxx} and this is what is pasted through magickeyboard instead of the actual password.

**Comment by J-Jamet** [comment]
It doesn't work with ref S because it is not implemented but should work with P and I.
@fritut08  Are you using the latest version of the application?

**Comment by fritut08** [comment]
Yes, it is the newest version

**Comment by J-Jamet** [comment]
Can you upload a test database that I can debug?

**Comment by fritut08** [comment]
I think I know, what the problem is. I created kind of a reference cascade 😄 

- Entry 1 has the password.
- Entry 2 references the password of entry 1.
- Entry 3 references the password of entry 2.

When I try to paste the password of entry 3 the UUID of entry 1 is pasted. So it does correctly dereference the first link but fails to check whether that entry also contains a reference. Keepass on desktop manages to find the correct password. Do you think you will be able to implement this or is this cascading too exotic? 😄

**Comment by J-Jamet** [comment]
This should be feasible but it can cause significant performance problems during searches because at each iteration, the field used as a reference (not necessarily a UUID) should be searched and this can be time consuming with a large database. I thought from memory that I had handled this case by having set a loop stop to avoid making infinite references but I may have broken the concept when I optimized the search. Can you open a new issue for this respecting the issue template (with a test database it would be great)?

**Comment by fritut08** [comment]
Yes, I will try. Thanks.
